name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build docker image
      #   working-directory: ./app-journey
      #   run: docker build -t karylchesman/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} .

      # - name: Push image
      #   working-directory: ./app-journey
      #   run: |
      #     docker push karylchesman/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }}
      #     docker tag karylchesman/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }} karylchesman/nlw-journey-devops:latest
      #     docker push karylchesman/nlw-journey-devops:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app-journey
          push: true
          tags: |
            karylchesman/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }}
            karylchesman/nlw-journey-devops:latest
